trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2.207.2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'

- task: DotNetCoreCLI@2.208.1
  inputs:
    command: 'publish'
    publishWebProjects: false
    zipAfterPublish: false
    modifyOutputPath: false
    arguments: --output $(Build.ArtifactStagingDirectory)

- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: 'NaukriResumeUpdate.dll.config'
    

- task: rename@0
  inputs:
    Command: 'rename'
    SourceFile: '$(Build.ArtifactStagingDirectory)/NaukriResumeUpdate.dll.config.local'
    NewName: 'NaukriResumeUpdate.dll.config'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'NaukriResumeUpdate'
